In [10]:
import numpy as np
np.random.seed(1)

In [11]:
# sigmoid function
# derivation 是否求导，如果 deriv 是 True 则回传求导后的值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [12]:
# X 的 initial value
X = np.array([  [1.0],
                [-1.0] ])
# y 的 initial value
y = np.array([[0.0, 1.0]]).T

print(X)
print(y)

[[ 1.]
 [-1.]]
[[0.]
 [1.]]


In [13]:
w1 = np.array([ [0.1, -0.3],
         [-0.2, 0.1],
         [0.2, -0.1] ])
b1 = np.array([[0.0, 0.2, -0.1]]).T
print('w1:\n', w1)
print('b1:\n', b1)

w1:
 [[ 0.1 -0.3]
 [-0.2  0.1]
 [ 0.2 -0.1]]
b1:
 [[ 0. ]
 [ 0.2]
 [-0.1]]


In [14]:
w2 = np.array([ [0.1, -0.1, 0.2],
         [0.3, 0.0, -0.1]])
b2 = np.array([[0.1, -0.1]]).T
print('w2:\n', w2)
print('b2:\n', b2)

w2:
 [[ 0.1 -0.1  0.2]
 [ 0.3  0.  -0.1]]
b2:
 [[ 0.1]
 [-0.1]]


In [15]:
learning_rate = 0.3

In [16]:
for iter in range(1):
    # forward propagation
    a0 = X # layer 0 即 input 一般会写作 X (注意是大写), 相当于 a0
    n1 = np.dot(w1, a0) + b1
    a1 = nonlin(n1).round(2) # 第1层 hidden layer 的 input 是 第0层的 activation function 后的 output
    print('a1\n', a1)
    n2 = np.dot(w2, a1) + b2
    a2 = nonlin(n2).round(2) # 相当于 a2
    print('a2\n', a2)
    a2_error = a2 - y
    print('a2_error\n', a2_error)

    a1_error = np.dot(w2.T, a2_error) * nonlin(a1, True)
    print('-----\nnonlin(a1, True)\n', nonlin(a1, True))
    print('np.dot(w2.T, a2_error)\n', np.dot(w2.T, a2_error))
    print('-----\na1_error\n', a1_error)

    # update weights
    w2 -= learning_rate * a2_error * a1.T 
    b2 -= learning_rate * a2_error 
    w1 -= learning_rate * a1_error * a0.T  
    b1 -= learning_rate * a1_error 


a1
 [[0.6 ]
 [0.48]
 [0.55]]
a2
 [[0.56]
 [0.51]]
a2_error
 [[ 0.56]
 [-0.49]]
-----
nonlin(a1, True)
 [[0.24  ]
 [0.2496]
 [0.2475]]
np.dot(w2.T, a2_error)
 [[-0.091]
 [-0.056]
 [ 0.161]]
-----
a1_error
 [[-0.02184  ]
 [-0.0139776]
 [ 0.0398475]]


In [17]:
print ("----------------\nOutput After Training:")
print ('w1\n', w1)
print ('w2\n', w2)
print ('b1\n', b1)
print ('b2\n', b2)

----------------
Output After Training:
w1
 [[ 0.106552   -0.306552  ]
 [-0.19580672  0.09580672]
 [ 0.18804575 -0.08804575]]
w2
 [[-0.0008  -0.18064  0.1076 ]
 [ 0.3882   0.07056 -0.01915]]
b1
 [[ 0.006552  ]
 [ 0.20419328]
 [-0.11195425]]
b2
 [[-0.068]
 [ 0.047]]


In [18]:
print( a2_error * a1.T)
print( a2_error )
print( a1_error * a0.T)
print( a1_error )

[[ 0.336   0.2688  0.308 ]
 [-0.294  -0.2352 -0.2695]]
[[ 0.56]
 [-0.49]]
[[-0.02184    0.02184  ]
 [-0.0139776  0.0139776]
 [ 0.0398475 -0.0398475]]
[[-0.02184  ]
 [-0.0139776]
 [ 0.0398475]]
