In [32]:
import numpy as np

In [33]:
# sigmoid function
# derivation 是否求导，如果 deriv 是 True 则回传求导后的值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [34]:
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
print(X)
    
# output dataset            
y = np.array([[0,0,1,1]]).T
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [0]
 [1]
 [1]]


In [35]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
# (3,1) means 3 rows 1 col
syn0 = 2*np.random.random((3,1)) - 1
print(syn0)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [36]:
for iter in range(10000):

    # forward propagation
    l0 = X # layer 0 即 input 一般会写作 X (注意是大写)
    l1 = nonlin(np.dot(l0,syn0)) # layer 1 即 第一层 hidden layer
    if iter == 0:
        print ("Output Before Training:")
        print(l1)

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # 用 error 即误差的大小 乘以
    # slope of the sigmoid at the values in l1 
    # 在 l1 的 sigmoid 的斜率
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print ("----------------\nOutput After Training:")
print (l1)


Output Before Training:
[[0.2689864 ]
 [0.36375058]
 [0.23762817]
 [0.3262757 ]]
----------------
Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
